# DO NOT EDIT this file! Cuz
# it imports modules
# and you have to edit the modules instead ahahahah
# you can also add more if u want

{
  imports = [
    # Include the results of the hardware scan.
    ./hardware-configuration.nix

    ./modules/boot.nix
    ./modules/hardware.nix
    ./modules/networking.nix
    ./modules/users.nix
    ./modules/userland.nix
    ./modules/audio.nix
    ./modules/sudo.nix
    ./modules/services.nix
    ./modules/programs.nix
  ];


  # This value determines the NixOS release from which the default
  # settings for stateful data, like file locations and database versions
  # on your system were taken. It‘s perfectly fine and recommended to leave
  # this value at the release version of the first install of this system.
  # Before changing this value read the documentation for this option
  # (e.g. man configuration.nix or on https://nixos.org/nixos/options.html).
  system.stateVersion = "26.05"; # Did you read the comment?

  nix.settings.experimental-features = [
    "nix-command"
    "flakes"
  ];
}
