{lib, ...}:{
  hardware.bluetooth = {
    enable = true;
    powerOnBoot = true;
    settings = {
      General = {
        Experimental = true;
        FastConnectable = true;
      };
      Policy = {
        AutoEnable = true;
      };
    };
  };

  environment.etc."libinput/local-overrides.quirks".text = lib.mkForce ''
    [keyd virtual keyboard]
    MatchName=keyd virtual keyboard
    AttrKeyboardIntegration=internal
    ModelTabletModeNoSuspend=1
  '';

  services.keyd = {
    # Configuration translated from cros.conf generated by WeirdTreeThing's script
    # Only for Jasper Lake!
    enable = true;
    keyboards = {
      cros = {
        ids = [ "k:18d1:502b"
          "k:18d1:5044"
          "k:18d1:503d"
          "k:18d1:505b"
          "k:0000:0000"
          "k:18d1:504c"
          "k:18d1:5061"
          "k:18d1:5052"
          "k:0001:0001"
          "k:18d1:5057"
          "k:18d1:503c"
          "k:18d1:5050"
          "k:18d1:5030" ];
        settings = {
          main = {
            f1 = "back";
            f2 = "refresh";
            f3 = "f11";
            f4 = "scale";
            f5 = "sysrq";
            f6 = "brightnessdown";
            f7 = "brightnessup";
            f8 = "mute";
            f9 = "volumedown";
            f10 = "volumeup";

            back = "back";
            refresh = "refresh";
            zoom = "f11";
            scale = "scale";
            sysrq = "sysrq";
            brightnessdown = "brightnessdown";
            brightnessup = "brightnessup";
            mute = "mute";
            volumedown = "volumedown";
            volumeup = "volumeup";

            f13="coffee";
            sleep="sleep";
          };
          meta = {
            f1 = "f1";
            f2 = "f2";
            f3 = "f3";
            f4 = "f4";
            f5 = "f5";
            f6 = "f6";
            f7 = "f7";
            f8 = "f8";
            f9 = "f9";
            f10 = "f10";

            back = "f1";
            refresh = "f2";
            zoom = "f3";
            scale = "f4";
            sysrq = "f5";
            brightnessdown = "f6";
            brightnessup = "f7";
            mute = "f8";
            volumedown = "f9";
            volumeup = "f10";
          };
          alt = {
            backspace = "delete";
            brightnessdown = "kbdillumdown";
            brightnessup = "kbdillumup";
            f6 = "kbdillumdown";
            f7 = "kbdillumup";
          };
          control = {
            f5 = "sysrq";
            scale = "sysrq";
          };
          altgr = {
            backspace = "delete";
            left = "home";
            right = "end";
            up = "pageup";
            down = "pagedown";
          };
          "control+alt" = {
            backspace = "C-A-delete";
            f1 = "C-A-f1";
            f2 = "C-A-f2";
            f3 = "C-A-f3";
            f4 = "C-A-f4";
            f5 = "C-A-f5";
            f6 = "C-A-f6";
            f7 = "C-A-f7";
            f8 = "C-A-f8";
            f9 = "C-A-f9";
            f10 = "C-A-f10";
            back = "C-A-f1";
            refresh = "C-A-f2";
            zoom = "C-A-f3";
            scale = "C-A-f4";
            sysrq = "C-A-f5";
            brightnessdown = "C-A-f6";
            brightnessup = "C-A-f7";
            mute = "C-A-f8";
            volumedown = "C-A-f9";
            volumeup = "C-A-f10";
          };
        };
      };
    }
    ;
  };
}
